# Generated by Django 4.1.1 on 2022-10-14 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_alter_contacts_birth_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contacts",
            new_name="Contact",
        ),
    ]
