# Generated by Django 4.1.1 on 2022-10-19 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_rename_contacts_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["contact_name"]},
        ),
    ]
