# Generated by Django 4.1.3 on 2022-11-12 12:48

from django.db import migrations, models

import apps.services.image_paths


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0004_alter_contact_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="contact_photo",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to=apps.services.image_paths.get_contact_photo_path
            ),
        ),
    ]
